---
- name: Pull docker image of speminiproject
  hosts: all
  tasks:
    - name: Pull speminiproject devops image
      docker_image:
        name: sreenidhikr/calculator
        pull: true
        source: pull
